// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu57qb8kO4NhDijVkx83UxmdqLJcmoUkY',
    appId: '1:533747396401:web:89bd3ef5a30abc1f078a10',
    messagingSenderId: '533747396401',
    projectId: 'scanner-aca88',
    authDomain: 'scanner-aca88.firebaseapp.com',
    storageBucket: 'scanner-aca88.appspot.com',
    measurementId: 'G-0V9Z5FFG7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYcEcwi5WPkJi8Ud4CGH8zhuugXHgmtc',
    appId: '1:533747396401:android:74b54c7798f66694078a10',
    messagingSenderId: '533747396401',
    projectId: 'scanner-aca88',
    storageBucket: 'scanner-aca88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13FQKlmKI4IHW-Uz_DeSwQ2NMjAuDxHc',
    appId: '1:533747396401:ios:d053abfa67c5cb16078a10',
    messagingSenderId: '533747396401',
    projectId: 'scanner-aca88',
    storageBucket: 'scanner-aca88.appspot.com',
    iosBundleId: 'com.example.faceId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13FQKlmKI4IHW-Uz_DeSwQ2NMjAuDxHc',
    appId: '1:533747396401:ios:d053abfa67c5cb16078a10',
    messagingSenderId: '533747396401',
    projectId: 'scanner-aca88',
    storageBucket: 'scanner-aca88.appspot.com',
    iosBundleId: 'com.example.faceId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu57qb8kO4NhDijVkx83UxmdqLJcmoUkY',
    appId: '1:533747396401:web:5a61acf216c68ad7078a10',
    messagingSenderId: '533747396401',
    projectId: 'scanner-aca88',
    authDomain: 'scanner-aca88.firebaseapp.com',
    storageBucket: 'scanner-aca88.appspot.com',
    measurementId: 'G-XCLMQGP7RX',
  );
}
